### ISSUE TITLE
Does not like all frequencies

### ISSUE THREAD

**Issue by FrankBoesing** [FrankBoesing/TeensyFMTransmitter#1]
Don't know why, but It does not like all frequencies.  
Maybe a BUG.  
So, if the sound quality is not good, try an other frequency. Make sure to use a free frequency.

**Comment by Defragster** [comment]
Not sure where this should be noted but quick scan of source saw the note on tau.  These two lines work the same in US:
`//AudioOutputFM            audioOutput(88, 50e-6f); //Frequency in MHz, preemphasis
AudioOutputFM            audioOutput(88, 75e-6f); //Frequency in MHz, preemphasis
`
107 and 88 work 

Using this :: AudioOutputFM            audioOutput(88.7, 75e-6f); //Frequency in MHz, preemphasis
Still registers as 88.0 on a digital FM radio.

But : AudioOutputFM            audioOutput(87.7, 75e-6f); //Frequency in MHz, preemphasis
Doesn't show up anywhere

Lots of float storage for math often done in double ...  should it all stay double?

**Comment by Defragster** [comment]
Just updated from github, freq 91.0 okay as well.

AudioOutputFM            audioOutput(33, 91.0, 75e-6f); //Pin (23= I2S1, 30= I2S3, 33= I2S2) , Frequency in MHz, preemphasis

**Comment by FrankBoesing** [comment]
Thank you for all the testing, Tim.

**Comment by Defragster** [comment]
No problem - always fun to 'egg you on'

Paul posted some short 'number' WAV files for mult or fast cycling sounds.  Should find those and add them - for SD 1.54 Beta test?  Not found them yet ...

Those music files are a bit repetitive - not always easy to know the sound isn't skipping.  First run after github update it seemed the buffer was in a cyclic loop with the same notes over and over

**Comment by Defragster** [comment]
https://forum.pjrc.com/threads/64235-Teensyduino-1-54-Beta-3?p=258095&viewfull=1#post258095

void loop() {
  playFile("num1.WAV");  // filenames are always uppercase 8.3 format
  delay(50);
  playFile("num2.WAV");  // filenames are always uppercase 8.3 format
  delay(50);
  playFile("num3.WAV");  // filenames are always uppercase 8.3 format
  delay(50);
  playFile("num4.WAV");  // filenames are always uppercase 8.3 format
  delay(50);
  playFile("num5.WAV");  // filenames are always uppercase 8.3 format
  delay(50);
  playFile("num6.WAV");  // filenames are always uppercase 8.3 format

**Comment by Defragster** [comment]
Another edit for faster play of those short sounds ....
<edit> this does uncontrolled Serial.print though ...
`void playFile(const char *filename)
{
  Serial.print("Playing file: ");
  Serial.println(filename);
  playWav1.play(filename);
  delay(25);
  while (playWav1.isPlaying()) {

    Serial.print("Diagnostics: ");
    Serial.print(AudioProcessorUsage());
    Serial.print("% ");

    Serial.println(AudioMemoryUsageMax());
    //delay(500);
  }
}

void loop() {
  playFile("num1.WAV");  // filenames are always uppercase 8.3 format
  // delay(5);
  playFile("num2.WAV");  // filenames are always uppercase 8.3 format
  // delay(5);
  playFile("num3.WAV");  // filenames are always uppercase 8.3 format
  delay(5);
  playFile("num4.WAV");  // filenames are always uppercase 8.3 format
  delay(5);
  playFile("num5.WAV");  // filenames are always uppercase 8.3 format
  delay(5);
  playFile("num6.WAV");  // filenames are always uppercase 8.3 format
  delay(5);
  playFile("SDTEST2.WAV");  // filenames are always uppercase 8.3 format
  delay(500);
  playFile("SDTEST3.WAV");
  delay(500);
  playFile("SDTEST4.WAV");
  delay(500);
  playFile("SDTEST1.WAV");
  delay(500);
}`

**Comment by FrankBoesing** [comment]
Should work now with ever frequency between 88 and 108 (and way less or more)

**Comment by FrankBoesing** [comment]
now fixed ;)
