### ISSUE TITLE
Pre-emphasis

### ISSUE THREAD

**Issue by DD4WH** [FrankBoesing/TeensyFMTransmitter#5]
I will provide a solution for a more sophisticated pre-emphasis algorithm later this evening or tomorrow.
Aim  is to implement this or a similar solution with flexible sample rate and cutoff frequency choice.
https://github.com/jontio/JMPX/blob/master/libJMPX/JDSP.cpp

**Comment by Defragster** [comment]
Have tried both EU/US values and either works here for that weird number.

**Comment by FrankBoesing** [comment]
The Hardware-Setup is now complete - we can add 4x samplerate now.. :)

Time, yes the difference is not that much. And maybe DD4WHs algorithm is better.

**Comment by DD4WH** [comment]
it amazing how things get complex, even if I thought that pre-emphasis is a very simple first order highpass filter and de-emphasis is a very simple first order lowpass filter.
I was not able to find anything on the web to properly explain how pre-emphasis is being done correctly and precisely. This is even more true for digital implementations. I experimented with different highpass filter algorithms, but using the time constants given, I was not successful, because the sound was too much emphasized in treble and much too low bass response. Jonti in his document reports the same lack of information . . .
In Jontis document he implements a highpass filter for emphasizing the treble freqs and a lowpass filter at 20kHz in order to cutoff all ultrasound using an IIR structure. The filter coefficients are calculated in a quite complex way and take care of the sample rate and the lowpass cutoff frequency and the time constant used in different parts of the world (50 or 75µsec).
The final result implemted sounds good to my ears . . .
What do you guys think ?
